# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry from git gub
  status: Connected to the JHipster Registry running in Docker from git hub

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YTQ5NjNkMTI4YzFjNDg2NjI5NmY4M2Q4ZmViM2UwOTQ5NGY5N2IxZTVlYjQzMWM5OTg1NDI1OGFhNGQ4ZTFkYjhiOWJjZmY1Mjk0NjUzMjMxMDY3NmQ2YTkxMDZjMmMzYmY1Mw==

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
